services:
  web:
    image: valenporfolio:latest
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.valenporfolio.rule=Host(`valentinvalverde.com`) || Host(`www.valentinvalverde.com`)"
      - "traefik.http.routers.valenporfolio.entrypoints=websecure"
      - "traefik.http.routers.valenporfolio.tls.certresolver=myresolver"
      - "traefik.docker.network=nextcloud_nextcloud_network"
      - "traefik.http.services.valenporfolio.loadbalancer.server.port=8080"
    expose:
      - 8080
    networks:
      - config_nextcloud_network
    restart: always

networks:
  config_nextcloud_network:
    external: true
