services:
  web:
    image: valenporfolio:latest
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8000:8080
    restart: always
