name: deploy-production

on:
  workflow_dispatch:
  push:
    branches:
      - production
    tags:
      - porfolio
      - production

env:
  registry_username: ${{ secrets.REGISTRY_USERNAME }}
  registry_password: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Npm install
      - name: Install dependencies
        run: npm install

      # Build webapp
      - name: Build webapp
        run: npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build webapp
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: false
          tags: valenporfolio:latest
          outputs: type=docker,dest=/tmp/valenporfolio.tar

      - name: Load image
        run: |
          docker load --input /tmp/valenporfolio.tar
          docker image ls -a

      - name: Tag image webapp
        run: docker tag valenporfolio:latest ghcr.io/${{ env.registry_username }}/valenporfolio:latest

      - name: Push webapp image
        run: docker push ghcr.io/${{ env.registry_username }}/valenporfolio:latest

      - name: Logout of docker registry
        run: docker logout

  deploy:
    runs-on: self-hosted
    needs:
      - build
    steps:
      - uses: actions/checkout@v3

      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Get image from registry
        run: docker pull ghcr.io/${{ secrets.REGISTRY_USERNAME }}/valenporfolio:latest

      - name: Tag webapp image
        run: docker tag ghcr.io/${{ secrets.REGISTRY_USERNAME }}/valenporfolio:latest valenporfolio:latest

      - name: Build containers
        run: docker compose -f docker-compose.yml up -d

      - name: Logout of docker registry
        run: docker logout

  cleanregistry:
    runs-on: self-hosted
    needs:
      - deploy
    steps:
      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Clean registry
        run: docker rmi $(docker images -q -f dangling=true)

      - name: Logout of docker registry
        run: docker logout
